version: '3'
services:
  node-app:
    image: my-node-app
    build: .
    ports:
      - "4000:4000"
    networks:
      - internal

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - internal
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
    restart: always

  node-app2:
    image: my-node-app
    build: .
    ports:
      - "4001:4000"
    networks:
      - internal
    depends_on:
      - nginx

networks:
  internal:
    driver: bridge
